# Generated by Django 6.0.4 on 2026-04-14 17:45

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product', primary_key=True, serialize=False)),
                ('name', models.CharField(default='product-6313747d-a29a-4704-8b9d-172211ca7992', help_text='Name for product', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for product', max_digits=10)),
                ('status', models.CharField(choices=[('a', 'Available'), ('d', 'Discontinued')], default='a', help_text='Product availability', max_length=1)),
            ],
            options={
                'ordering': ['product_model', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for city', primary_key=True, serialize=False)),
                ('name', models.CharField(default='city-9d1d2bed-bb22-44dd-b06a-d89910bfecc8', help_text='Name of city', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='city_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for phone', primary_key=True, serialize=False)),
                ('phone', models.CharField(default='+375 (29) 000-00-00', help_text='Phone number of client', max_length=19)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('phone'), name='phone_case_insensitive_unique', violation_error_message='Phone already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text="Client's unique ID", primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='company-ae19264f-6481-45fd-890a-6b11b197a76a', help_text="Client's company name", max_length=100)),
                ('address', models.CharField(help_text="Client's address", max_length=100)),
                ('phone', models.OneToOneField(help_text="Client's phone", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.phone')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for pick-up point', primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Address of pick-up point', max_length=100)),
                ('city', models.ForeignKey(help_text='City of pick-up point', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.city')),
            ],
            options={
                'ordering': ['city', 'address'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for order', primary_key=True, serialize=False)),
                ('date_order_create', models.DateField(default=datetime.date.today, help_text='Date of create order')),
                ('date_order_complete', models.DateField(blank=True, help_text='Date of complete order', null=True)),
                ('product_amount', models.PositiveIntegerField(default=1, help_text='Amount of products in order')),
                ('client', models.ForeignKey(help_text='Client of order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.client')),
                ('product', models.ForeignKey(help_text='Client order of product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.product')),
            ],
            options={
                'ordering': ['date_order_create', 'client', 'product', 'product_amount'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product model', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product model name', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='product_model_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(help_text='Model for product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.productmodel'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product type', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product type name', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='product_type_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(help_text='Type for product', to='ToyFactory.producttype'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birth_date', models.DateField(help_text='Date of birth')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('company_name'), name='company_name_case_insensitive_unique', violation_error_message='Company name already exists (case insensitive match)'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='product_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)'),
        ),
    ]
