# Generated by Django 6.0.4 on 2026-04-13 18:28

import datetime
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product', primary_key=True, serialize=False)),
                ('name', models.CharField(default='product-22955dcd-d25f-4fa4-aab4-0e8b32adc50a', help_text='Name for product', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for product', max_digits=10)),
                ('status', models.CharField(choices=[('a', 'Available'), ('d', 'Discontinued')], default='a', help_text='Product availability', max_length=1)),
            ],
            options={
                'ordering': ['product_type', 'product_model'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for city', primary_key=True, serialize=False)),
                ('name', models.CharField(default='city-2a8df2a9-d621-4c9b-be1f-b9ef0f2ae0d2', help_text='Name of city', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='city_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for phone', primary_key=True, serialize=False)),
                ('phone', models.CharField(default='+375 (29) 000-00-00', help_text='Phone number of client', max_length=19)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('phone'), name='phone_case_insensitive_unique', violation_error_message='Phone already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text="Client's unique ID", primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='company-9e8d6071-e888-42d8-a7f0-7807871fe57d', help_text="Client's company name", max_length=100)),
                ('address', models.CharField(help_text="Client's address", max_length=100)),
                ('phone', models.OneToOneField(help_text="Client's phone", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.phone')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for pick-up point', primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Address of pick-up point', max_length=100)),
                ('city', models.ForeignKey(help_text='City of pick-up point', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.city')),
            ],
            options={
                'ordering': ['city', 'address'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for order', primary_key=True, serialize=False)),
                ('date_order_create', models.DateField(default=datetime.date.today, help_text='Date of create order')),
                ('date_order_complete', models.DateField(help_text='Date of complete order', null=True)),
                ('product_amount', models.PositiveIntegerField(default=1, help_text='Amount of products in order')),
                ('client', models.OneToOneField(help_text='Client of order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.client')),
                ('product', models.ForeignKey(help_text='Client order of product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.product')),
            ],
            options={
                'ordering': ['date_order_create', 'client', 'product', 'product_amount'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product model', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product model name', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='product_model_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(help_text='Model for product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.productmodel'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product type', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product type name', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='product_type_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(help_text='Type for product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.producttype'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('company_name'), name='company_name_case_insensitive_unique', violation_error_message='Company name already exists (case insensitive match)'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='product_name_case_insensitive_unique', violation_error_message='Name already exists (case insensitive match)'),
        ),
    ]
