# Generated by Django 6.0.4 on 2026-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_model', 'name']},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-6ff05bba-a7b4-412f-9a9f-d8e28adba4c7', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='company-3cce335c-3131-4680-81df-dcd188a4035e', help_text="Client's company name", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-d0fad7e3-2243-42b3-8665-d0e59eaafb11', help_text='Name for product', max_length=100),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(help_text='Type for product', to='ToyFactory.producttype'),
        ),
    ]
