# Generated by Django 6.0.4 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-08de6a13-1989-40b0-9560-57ab52b18959', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='company-6c7511c9-3c44-4184-9320-5847c6a36955', help_text="Client's company name", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-e4cfc326-1783-48a9-8da9-30aec331cee8', help_text='Name for product', max_length=100),
        ),
    ]
