# Generated by Django 6.0.4 on 2026-04-14 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0002_alter_city_name_alter_client_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-cf30a549-3275-470e-b8e4-9043f30efe02', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='company-eb8a5819-25e6-4342-acc8-f12b786474bf', help_text="Client's company name", max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateField(default=datetime.date.today, editable=False, help_text='Date of create order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-3d52c74c-1d66-4d3e-bf28-589998823837', help_text='Name for product', max_length=100),
        ),
    ]
