# Generated by Django 6.0.4 on 2026-04-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0002_alter_product_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-5ae55827-174a-49ac-83c9-d8aa28086be7', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='company-c54f88fb-f234-4f32-b23f-986c55ee3be1', help_text="Client's company name", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-e7ef6fdc-d118-4f29-b6e5-4288bbe9b4dd', help_text='Name for product', max_length=100),
        ),
    ]
