# Generated by Django 6.0.4 on 2026-04-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0003_alter_city_name_alter_client_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-54907386-8dd4-45b6-8e16-8d7840995585', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='company-720fe13c-cc61-48d9-8290-82b3805b3e06', help_text="Client's company name", max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='Client of order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_complete',
            field=models.DateField(blank=True, help_text='Date of complete order', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-182a617f-87b6-4caa-9267-75697a206194', help_text='Name for product', max_length=100),
        ),
    ]
