# Generated by Django 6.0.4 on 2026-04-15 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0003_alter_city_name_alter_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=1998, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for city', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-9664b5a2-99b1-4128-94a3-a6fe2c4ed2fd', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(help_text="Client's company name", max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Client's unique ID", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.OneToOneField(help_text="Client's phone", null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='Client of order', null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for order', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(help_text='Client order of product', null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.product'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for phone', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='city',
            field=models.ForeignKey(help_text='City of pick-up point', null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.city'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for pick-up point', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for product', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-43badbba-d5a1-4000-aa70-2324c5ee3b9e', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(help_text='Model for product', null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for product model', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for product type', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for phone', primary_key=True, serialize=False)),
                ('info', models.CharField(default='Promo code for any orders', help_text='Promo code for clients', max_length=50)),
                ('sale', models.DecimalField(decimal_places=2, default=0.1, help_text='Sale for order', max_digits=3)),
                ('client', models.ForeignKey(help_text="Client's promo code", on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.client')),
            ],
            options={
                'ordering': ['client', 'sale'],
            },
        ),
    ]
