# Generated by Django 6.0.4 on 2026-04-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0004_client_user_alter_city_id_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-a3f94a85-6798-4905-8953-dd7006bcc37a', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-d542094b-3b6b-4fc4-b739-478f02391f53', help_text='Name for product', max_length=100),
        ),
    ]
