# Generated by Django 6.0.4 on 2026-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0005_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-0b4b0fcb-eb0c-4f1e-9a93-4d5abf054e43', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-7319ec8d-57e8-4686-8a2d-b2244e1fa16e', help_text='Name for product', max_length=100),
        ),
    ]
