# Generated by Django 6.0.4 on 2026-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0007_alter_city_name_alter_product_name_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-00ada32c-70b7-4155-8f3b-933f4f0b8d96', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-d1ab2b2a-d02b-41e0-b397-94a604feb293', help_text='Name for product', max_length=100),
        ),
    ]
