# Generated by Django 6.0.4 on 2026-04-15 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0008_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermissions',
            options={'managed': False, 'permissions': (('employee_perm', 'Employee permissions'), ('client_perm', 'Client permissions'))},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-ded69cf6-9bfa-40ac-a03e-b3e26a70ae2c', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-bd394862-748b-4d52-a0f2-288b545441ec', help_text='Name for product', max_length=100),
        ),
    ]
