# Generated by Django 6.0.4 on 2026-04-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0009_alter_apppermissions_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-fb015c84-5f2d-45ea-bd95-5698799d3e78', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-ef2c0b84-2a53-42bd-be66-7764ff28f2c6', help_text='Name for product', max_length=100),
        ),
    ]
