# Generated by Django 6.0.4 on 2026-04-16 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0010_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, help_text="Image for Employee's profile", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='info',
            field=models.CharField(blank=True, help_text="Info about employee's tasks", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.OneToOneField(blank=True, help_text="Employee's phone", null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.phone'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-da849e62-000e-4e2e-87f1-4c33629d10fe', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.OneToOneField(help_text="Client's phone", on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.phone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-232dc833-ef54-4316-a7fa-c047fd8c6b2f', help_text='Name for product', max_length=100),
        ),
    ]
