# Generated by Django 6.0.4 on 2026-04-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0011_employee_image_employee_info_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-18301b48-16bf-46e9-b206-00911c5f85e8', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='info',
            field=models.CharField(blank=True, default='Employee of Toy Factory', help_text="Info about employee's tasks", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.OneToOneField(help_text="Employee's phone", on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.phone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-4dcf986a-ea6a-4dac-b14b-cd651efdcc73', help_text='Name for product', max_length=100),
        ),
    ]
