# Generated by Django 6.0.4 on 2026-04-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0012_alter_city_name_alter_employee_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-e02f9e57-1949-4340-af0a-b2cea24572af', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-01a2e140-b4f5-4b0f-8ca6-24e057d0d279', help_text='Name for product', max_length=100),
        ),
    ]
