# Generated by Django 6.0.4 on 2026-04-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0013_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-40d33e4a-ae41-47e3-a920-4e1ee7c35036', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-06214074-a0f8-41a9-abe3-f0deb2dbee15', help_text='Name for product', max_length=100),
        ),
    ]
