# Generated by Django 6.0.4 on 2026-04-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0014_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-30c5b99a-3abf-4a77-b4ef-0077413e1b4a', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-b185b45f-8f63-45b3-be59-5af9cfa693aa', help_text='Name for product', max_length=100),
        ),
    ]
