# Generated by Django 6.0.4 on 2026-04-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0016_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-30d700bc-8273-45dd-8417-6291cad87bdd', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-f952e4d6-6ec2-4655-b217-1067aadaebd4', help_text='Name for product', max_length=100),
        ),
    ]
