# Generated by Django 6.0.4 on 2026-04-16 08:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0017_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Header for Company Info', max_length=100)),
                ('info', models.TextField(help_text='Description for Company')),
                ('logo', models.ImageField(help_text='Logotype for Company', upload_to='')),
                ('pub_date', models.DateField(default=datetime.date(2026, 4, 16), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question', max_length=200)),
                ('answer', models.TextField(help_text='Answer')),
                ('pub_date', models.DateField(default=datetime.date(2026, 4, 16), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Header for News', max_length=400)),
                ('info', models.TextField(help_text='Description of News')),
                ('image', models.ImageField(help_text='Image for news', upload_to='')),
                ('pub_date', models.DateField(default=datetime.date(2026, 4, 16), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for Vacancy', max_length=200)),
                ('info', models.TextField(help_text='Description of Vacancy')),
                ('requirements', models.TextField(help_text='Requirements of Vacancy')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salary for this vacancy', max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-f44b7869-a374-4d8b-94d4-9947800c1d1c', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-5610ab82-6f8e-4abd-821e-1b427186d184', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(help_text='Model for product', on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.productmodel'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(help_text="User's review", max_length=500)),
                ('grade', models.PositiveIntegerField(default=5, help_text="User's grade", validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('pub_date', models.DateField(default=datetime.date(2026, 4, 16), editable=False)),
                ('user', models.ForeignKey(help_text="Review's user", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
