# Generated by Django 6.0.4 on 2026-04-16 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0018_aboutinfo_faq_news_vacancy_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-3188d300-5c74-4697-ad3b-4d105673f3ea', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-ae3681f7-912a-48b3-981c-463e6352ef69', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
