# Generated by Django 6.0.4 on 2026-04-16 11:08

import datetime
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0019_alter_aboutinfo_pub_date_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['sale']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='promo',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='promos',
            field=models.ManyToManyField(help_text='Promos for clients', to='ToyFactory.promo'),
        ),
        migrations.AddField(
            model_name='promo',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 4, 23)),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-543b0374-58ad-4165-b804-2208f8e8090c', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-09621520-3258-40ba-9a34-07934d4d9d68', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Sale for order', max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddConstraint(
            model_name='faq',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('question'), name='question_case_insensitive_unique', violation_error_message='Question already exists (case insensitive match)'),
        ),
    ]
