# Generated by Django 6.0.4 on 2026-04-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0020_alter_aboutinfo_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='promos',
        ),
        migrations.AddField(
            model_name='promo',
            name='product',
            field=models.ForeignKey(blank=True, help_text="Product's promo", null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.product'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-dedd8619-aebb-4d94-8ca2-0a171fb7ae99', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-57a6c3f5-a7d3-40f4-abe8-78d701ca18fe', help_text='Name for product', max_length=100),
        ),
    ]
