# Generated by Django 6.0.4 on 2026-04-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0021_remove_client_promos_promo_product_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-979c8cc6-014e-44c5-8432-147e6245f3ee', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-fdc5faa4-b640-40b5-baff-aa4f8a580d80', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='product',
            field=models.ForeignKey(help_text="Product's promo", on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.product'),
        ),
    ]
