# Generated by Django 6.0.4 on 2026-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0022_alter_city_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-8b305e8a-9c8a-4c26-8cdd-3ed8ce35a4ac', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-99bd6556-c52d-4c31-a723-35a441444683', help_text='Name for product', max_length=100),
        ),
    ]
