# Generated by Django 6.0.4 on 2026-04-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0023_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-5d35f2ea-58a5-4c82-98fc-b77cc1ddd6d7', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-bd937e29-af72-48f2-bbad-398f7849d969', help_text='Name for product', max_length=100),
        ),
    ]
