# Generated by Django 6.0.4 on 2026-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0024_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='logo',
            field=models.ImageField(blank=True, default='default_about_logo.png', help_text='Logotype for Company', upload_to=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-579bca79-d56e-4451-b95f-a22e527434be', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default_employee_logo.png', help_text="Image for Employee's profile", upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='default_news_logo.png', help_text='Image for news', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-673bee2a-1474-4c88-8d04-b747f27d727d', help_text='Name for product', max_length=100),
        ),
    ]
