# Generated by Django 6.0.4 on 2026-04-16 21:07

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0025_alter_aboutinfo_logo_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-a5ac8556-0438-41e9-93a8-fabc86899de8', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-b0cb536a-f617-445b-b6b7-6756769b82d2', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 4, 24)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
