# Generated by Django 6.0.4 on 2026-04-16 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0026_alter_aboutinfo_pub_date_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-453d67af-91fa-48b8-84a2-b58bc761459d', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_amount',
            field=models.PositiveIntegerField(default=1, help_text='Amount of products in order', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-51de1bf7-85b5-4cf1-8ba1-ee15ab745fce', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for product', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Salary for this vacancy', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
