# Generated by Django 6.0.4 on 2026-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0027_alter_city_name_alter_order_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-0787184e-c024-48da-9c54-29649ed905ab', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-0d1fa77a-c0bf-457c-8e78-bd39b2a08cea', help_text='Name for product', max_length=100),
        ),
    ]
