# Generated by Django 6.0.4 on 2026-04-17 11:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0028_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-76e1dcd4-83a5-4004-87b6-a3d732164593', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-7757cf5e-0fae-4b5a-ad72-fdf27fe81839', help_text='Name for product', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='title_case_insensitive_unique', violation_error_message='Title for vacancy already exists (case insensitive match)'),
        ),
    ]
