# Generated by Django 6.0.4 on 2026-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0029_alter_city_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-e86f2811-7561-49b0-8db4-88f73f2c24f6', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-53fb7882-8135-4e9b-abb2-bf7e7bcadf06', help_text='Name for product', max_length=100),
        ),
    ]
