# Generated by Django 6.0.4 on 2026-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0030_alter_review_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-5a9e0a1e-1cfb-4967-9a95-642ec7d74516', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-43eaba46-673a-46d1-bac7-efd4b4673f1f', help_text='Name for product', max_length=100),
        ),
    ]
