# Generated by Django 6.0.4 on 2026-04-17 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0031_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-be77878d-5f51-4a16-8327-93e5e810d6da', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-9f2c9a75-eeee-431d-906d-6abb5b303a24', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 4, 25)),
        ),
    ]
