# Generated by Django 6.0.4 on 2026-04-18 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0032_alter_city_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['status', 'price', 'product_model', 'name']},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-5c889b7f-a44e-46ee-acaa-eb001ee4e30a', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateField(default=datetime.date.today, help_text='Date of create order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-502d9cbc-3451-40e3-8e26-fcba44ceacd5', help_text='Name for product', max_length=100),
        ),
    ]
