# Generated by Django 6.0.4 on 2026-04-18 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0033_alter_product_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_order_create', 'product_amount', 'product']},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-38d9e3dd-59c9-4aab-82c8-88e11e5ede17', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of create order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-8e93c14a-1886-4852-bf1b-1834bfafdf43', help_text='Name for product', max_length=100),
        ),
    ]
