# Generated by Django 6.0.4 on 2026-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0034_alter_order_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_order_create', '-product_amount', 'product']},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-1478d34a-b77a-4706-8a4a-3e23681c76c6', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-7cb11617-ca47-4b7b-9dfc-861beba9e3b8', help_text='Name for product', max_length=100),
        ),
    ]
