# Generated by Django 6.0.4 on 2026-04-18 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0035_alter_order_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-87e8a3d9-ecfc-448a-868e-ab0c6e26174d', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of create order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-1b0a9c63-5c44-4d48-b2a7-d09cf56134f7', help_text='Name for product', max_length=100),
        ),
    ]
