# Generated by Django 6.0.4 on 2026-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0036_alter_city_name_alter_order_date_order_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-1e12ca21-cf80-46f7-9c2a-c7a875d64102', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_complete',
            field=models.DateTimeField(blank=True, help_text='Date of complete order', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-4b7273b6-1c56-4024-9179-e386232bc3a8', help_text='Name for product', max_length=100),
        ),
    ]
