# Generated by Django 6.0.4 on 2026-04-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0037_alter_city_name_alter_order_date_order_complete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_order_create', '-product_amount', 'product']},
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(blank=True, help_text="Clients's city", null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-04e496e8-ecc0-4e59-b5b1-af7b8ad5f60e', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-526f99dd-23c9-425a-9dab-16f4709dc8ba', help_text='Name for product', max_length=100),
        ),
    ]
