# Generated by Django 6.0.4 on 2026-04-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0038_alter_order_options_client_city_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-7380cb15-dcc3-4da4-a080-40a88f371eb3', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(help_text="Clients's city", on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.city'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-08ef7bd5-94d1-44e2-bf0c-bd8a5a83e341', help_text='Name for product', max_length=100),
        ),
    ]
