# Generated by Django 6.0.4 on 2026-04-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0039_alter_city_name_alter_client_city_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pick_up_point',
            field=models.ForeignKey(blank=True, help_text="Client's pick-up point", null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-7ef9a65b-30c4-4736-ae48-40f3952d5055', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-b3e2cfd8-1d1a-4a5f-87a7-175b6f04b5db', help_text='Name for product', max_length=100),
        ),
    ]
