# Generated by Django 6.0.4 on 2026-04-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0040_client_pick_up_point_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-6604c62c-5b1a-435b-adda-d8c0b168f965', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pick_up_point',
            field=models.ForeignKey(help_text="Client's pick-up point", on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-95250bba-47a6-4741-8468-c5b31c8abd51', help_text='Name for product', max_length=100),
        ),
    ]
