# Generated by Django 6.0.4 on 2026-04-18 22:21

import ToyFactory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0041_alter_city_name_alter_client_pick_up_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, help_text='Applied promo code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToyFactory.promo'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-bdd5a6e6-03c9-4a26-a236-5b09316e730f', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='Client of order', on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.client'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-ef2c4afb-01f6-45a1-b23c-2c7656dfbca6', help_text='Name for product', max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateField(default=ToyFactory.models.Promo.get_default_end_date),
        ),
    ]
