# Generated by Django 6.0.4 on 2026-04-18 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0042_order_promo_alter_city_name_alter_order_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pick_up_point',
        ),
        migrations.AddField(
            model_name='order',
            name='pick_up_point',
            field=models.ForeignKey(blank=True, help_text="Client's pick-up point", null=True, on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-1effe362-bf5f-41ec-9972-952911c5bf37', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-75cc7928-1a28-4d18-9fbf-8ae018a4444e', help_text='Name for product', max_length=100),
        ),
    ]
