# Generated by Django 6.0.4 on 2026-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0043_remove_client_pick_up_point_order_pick_up_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-e6fd2f90-7027-4fb7-8195-78e1c6a9a569', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-6e0f7f2d-4e87-4ebb-b874-28c81b803d8b', help_text='Name for product', max_length=100),
        ),
    ]
