# Generated by Django 6.0.4 on 2026-04-18 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0044_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-b3daf924-a336-47aa-a0fd-02ec9a76f80d', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_point',
            field=models.ForeignKey(help_text="Client's pick-up point", on_delete=django.db.models.deletion.CASCADE, to='ToyFactory.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-b8397106-1136-4810-b726-61943ccfe549', help_text='Name for product', max_length=100),
        ),
    ]
