# Generated by Django 6.0.4 on 2026-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0045_alter_city_name_alter_order_pick_up_point_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['city', 'company_name']},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-d0f8f476-56dd-4463-a6d3-71b672a5a013', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-339ea035-7d43-4871-93ea-079923acbef5', help_text='Name for product', max_length=100),
        ),
    ]
