# Generated by Django 6.0.4 on 2026-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0046_alter_client_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-01e3236b-1f8a-4ef4-a46a-90c03c39ad21', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-5399005b-9a9b-4e97-8d3e-daab9de78ab2', help_text='Name for product', max_length=100),
        ),
    ]
