# Generated by Django 6.0.4 on 2026-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0048_aboutinfo_created_at_aboutinfo_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='aboutinfo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-9ca6da76-df77-4264-8ded-1bc6c59d05c0', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-ecf24d77-607f-4ba2-91b0-95f23688bf81', help_text='Name for product', max_length=100),
        ),
    ]
