# Generated by Django 6.0.4 on 2026-04-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0049_alter_aboutinfo_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-e5b806bd-5fc0-4538-b317-ea6cbf84fe03', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-81a6d9e5-c3b6-4604-a475-49288277678a', help_text='Name for product', max_length=100),
        ),
    ]
