# Generated by Django 6.0.4 on 2026-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0050_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-65449346-1528-4f5c-933b-23e53dcb412e', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-e80e8901-42e9-4e6a-b48c-c04df3be3475', help_text='Name for product', max_length=100),
        ),
    ]
