# Generated by Django 6.0.4 on 2026-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0051_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-432d0ad1-1716-4a34-80ac-4e3125859b19', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-cfc19d78-c72d-4842-9129-eaec0532ad56', help_text='Name for product', max_length=100),
        ),
    ]
