# Generated by Django 6.0.4 on 2026-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0052_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-b70b3db0-95f9-4c1d-819f-a2f87945a354', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-4bd626df-58ff-4bab-a580-a16e7e858f23', help_text='Name for product', max_length=100),
        ),
    ]
