# Generated by Django 6.0.4 on 2026-04-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0053_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-9080ac0e-88de-4a71-ab64-b578bc47f72c', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, help_text="Image for Employee's profile", upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-e5c2c8ce-a980-45dd-8efd-2c66c015d1fc', help_text='Name for product', max_length=100),
        ),
    ]
