# Generated by Django 6.0.4 on 2026-04-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0054_alter_city_name_alter_employee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-6298203e-5910-4f2d-b82c-f0bc6facdcb3', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-9fc7d70e-584d-45a6-becb-7eeb2e939584', help_text='Name for product', max_length=100),
        ),
    ]
