# Generated by Django 6.0.4 on 2026-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0055_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-3afe4d1a-36b7-407d-a846-f829149b8bb2', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-b7c42963-7c98-4bb4-bc7a-3123528d65a0', help_text='Name for product', max_length=100),
        ),
    ]
