# Generated by Django 6.0.4 on 2026-04-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0056_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-f5a365c1-f951-40eb-944f-15c810238752', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateTimeField(help_text='Date of create order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-31553a48-2936-4f86-b807-906e4cad6dd2', help_text='Name for product', max_length=100),
        ),
    ]
