# Generated by Django 6.0.4 on 2026-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0057_alter_city_name_alter_order_date_order_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-965f16c8-cf9f-4ed6-80aa-832a5531efb8', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-a39052db-eb59-488b-98a5-19c0ac690450', help_text='Name for product', max_length=100),
        ),
    ]
