# Generated by Django 6.0.4 on 2026-09-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0058_alter_city_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='certificate',
            field=models.ImageField(blank=True, help_text='Company certificate', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='history',
            field=models.TextField(blank=True, help_text='History by years (text or list)'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='requisites',
            field=models.TextField(blank=True, help_text='Company requisites (Bank account, UNP, etc.)'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='video',
            field=models.FileField(blank=True, help_text='Company promotional video (mp4)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-ca6c86e2-3dcd-4fc8-9177-14a8e935c2b1', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-e22c7d03-e453-4b2d-8f7a-8fc603059e47', help_text='Name for product', max_length=100),
        ),
    ]
