# Generated by Django 6.0.4 on 2026-09-08 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0059_aboutinfo_certificate_aboutinfo_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='Краткое описание новости.', help_text='Short description (one sentence)', max_length=250),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-302274ab-3793-4c2b-a471-bd23d28d5e10', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for news', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='info',
            field=models.TextField(help_text='Full text of News article'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-7415a49d-3ffd-4059-be1e-53fc8fbd156a', help_text='Name for product', max_length=100),
        ),
    ]
