# Generated by Django 6.0.4 on 2026-09-09 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToyFactory', '0060_alter_news_options_news_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for Partner', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company partner name', max_length=150)),
                ('website_url', models.URLField(help_text="URL to partner's website")),
                ('logo', models.ImageField(blank=True, help_text="Partner's logo image", null=True, upload_to='partners/')),
                ('description', models.CharField(blank=True, help_text='Short info about partnership', max_length=250)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры компании',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='city-a03f3c53-7489-423e-be4f-525e57606b2d', help_text='Name of city', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product-183ca374-ea49-4963-9120-47e2dc73b495', help_text='Name for product', max_length=100),
        ),
    ]
